### ISSUE TITLE
Better Support for Carsharing 

### ISSUE THREAD

**Issue by hunterowens** [openmobilityfoundation/mobility-data-specification#383]
placeholder.

**Comment by Liyubov** [comment]
Are there separate rules for describing car-sharing (vs. just car driving)?
The same questions is about the independent vehicles information e.g.
https://www.tandfonline.com/doi/abs/10.1080/10630732.2018.1493883

**Comment by thekaveman** [comment]
@hunterowens it seems like this issue came on the heels of #219 - do you have more context into what improvements you would like to see?

**Comment by schnuerle** [comment]
Would like to discuss ideas on what else would need to be changed to support carsharing.

Since this was suggested there is a car vehicle type now, and I think some cities are using MDS for carshare already.

https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/general-information.md#vehicle-types

**Comment by schnuerle** [comment]
I'm going to close this issue in favor of #640 which has more detailed description/use cases outlined, and more discussion.
