### ISSUE TITLE
Policy: UUID specification for Geographies is unspecified

### ISSUE THREAD

**Issue by ascherkus** [openmobilityfoundation/mobility-data-specification#433]
**Describe the bug**
Neither the README.md nor the examples.md contains a specification / example of how / where to specify the UUID for a GeoJSON feature.

For example, in the Flat Files example the policy objects in policies.json reference UUIDs that should be contained in geographies.json, but there is no description nor example of where that UUID is stored (at least that I could find!).

**To Reproduce**
Steps to reproduce the behavior: N/A

**Expected behavior**
A specification with an example of geographies associated with policies should be present for the specification to be easily implementable by others.

If I totally missed where this is specified (a possibility I'm willing to admit) - then I'm happy to take a crack adding some appropriate links / references.

**Additional context**
Came across this while prototyping a tool for #423.

**Comment by avatarneil** [comment]
@ascherkus I'm pretty sure you didn't miss anything -- it looks like there's not actually a definition of the structure of `Geography` in the spec. The reason we didn't initially include this in the Policy PR is because we intend to have the `Geography` type used elsewhere in the future, and wanted it to be a shared type between multiple services (e.g Agency, Policy, whatever is coming next). For now, I think it makes sense to add it to the Policy spec, as well as an example or two. The rough structure to get you started is: `{ geography_id: UUID, geography_json: GeoJson<FeatureCollection> }`. We'll cut a PR to resolve this, thanks for pointing it out!

**Comment by schnuerle** [comment]
@karcass since you assigned this to yourself, how do you think this can be addressed for 1.0.0?

**Comment by janedotx** [comment]
@ascherkus @schnuerle The schema outlined in the Geography PR does include the `uuid`: https://github.com/openmobilityfoundation/mobility-data-specification/pull/499/files

So I think merging that in should cover the problem.

**Comment by schnuerle** [comment]
PR #499 is not scheduled for this 1.0.0 release so if we want it sooner, it would have to be done in a smaller PR now.

**Comment by janedotx** [comment]
@schnuerle Ok, I can cut a PR to flesh out the schema in `Policy` and we can merge it in

**Comment by schnuerle** [comment]
Resolved with #533 thank you @janedotx for the quick work!  Larger solution in #499 coming later.
