### ISSUE TITLE
Include state machine diagram in Vehicle State docs

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mobility-data-specification#524]
After #506 is merged, we'll have a reconciled state machine between Agency and Provider. We've been working on an [updated state machine diagram](https://docs.google.com/presentation/d/1Ar2-ju8YlddSsTATvQw4YjsSa5108XtidtnJNk-UAfA/edit), and it would be helpful to include an image of this diagram directly inline with the new docs on Vehicle State introduced with #506.

**Comment by schnuerle** [comment]
I think the State Machine Diagram (SMD) should live as a file in the repo.  

1) Where should the file go? At the root level, maybe in /schema, or in a new folder (eg, /resources)?

2) I think it should be a SVG file since that renders well on Github. Could also be a PNG.  Thoughts?

**Comment by thekaveman** [comment]
SVG as long as it is easy to update. If we're just going from the Google Doc and it can be exported, then whatever format is supported for export is fine by me.

**Comment by schnuerle** [comment]
SVG, PNG, JPG, and PDF are all export options.  Easy to update since any change can then be exported as SVG again.

Can also export as PowerPoint, so anyone could take that file and modify (if we store the file in a repo).  We could provide a link to the Google Slides under the diagram so people can grab that, and make changes if they want.

**Comment by schnuerle** [comment]
Completed.
