### ISSUE TITLE
Consider representing "unauthorized" movement in reconciled state machine

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mobility-data-specification#527]
From @billdirks on #506:

> Do we want an event transition for when a scooter gets moved in an "unauthorized" way. For example, a random person physically picking up an available vehicle walking a block and then putting it down (an `available` to `available` transition in this case)? I saw this as an inline question in the google doc at one point but don't know if there was any conversation about this.

**Comment by johnclary** [comment]
Can we flesh out the use case for this and clarify that in the title? It reads like we're talking about policing riders.

**Comment by schnuerle** [comment]
We will be talking about this on the Working Group call tomorrow: https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2020.10.01-(Joint-Working-Group-City-Services)

**Comment by schnuerle** [comment]
Hi @billdirks we talked about this at the WG meeting.  

Vianova said this may be needed when a device is being moved between operational zones. Alex in SF said `unknown` might be enough to know, and Thibault agreed. Kegan in Santa Monica said this came up in regard to cap counting, but that was before the `unknown` state existed. 

So the consensus is that the new states and events that are available now should cover 'unauthorized' vehicle movement.  While a provider knows when this happens (eg when a locked device is moved and an alarm goes off), we didn't think it needed to be returned for any city use cases. 

What are your thoughts on this, do you have any specific use cases, and do you think the new events cover this?

**Comment by billdirks** [comment]
The use case here is operational and not about policing riders. My concern was about events that move the location of unused scooters on the PROW that can't be represented by MDS. This is because we generate a map of scooter locations from playing through status events. If one is using the map to locate a scooter (eg some agencies wanted to remove scooters from the street during recent protests) sometimes it could be difficult to find because it was moved and the operator couldn't signal that through MDS. For example, a random person (ie not a rider) may pick up a scooter walk a block and then put it down.

Note, when this issue was brought up the `unknown` state was unavailable and the `/vehicles` endpoint was in beta as it is now.

It seems like we could now represent this happening my transitioning to the `unknown` state when the vehicle is picked up and then transitioning from the `unknown` state when the scooter is dropped off somewhere.

We can close this ticket.

**Comment by schnuerle** [comment]
Thanks Bill for the details and thoughts.  Agree we can close this now. If anyone has feedback or would like it to be reopened for a specific use case, please let us know in a comment.
