### ISSUE TITLE
'maintenance' event has two different definitions

### ISSUE THREAD

**Issue by vilesa1** [openmobilityfoundation/mobility-data-specification#595]
Hello

As per: https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/general-information.md#vehicle-states

'maintenance' is defined as a transition (1) from 'available' state to 'non_operational' state ("The vehicle requires some non-charge-related maintenance")

however it seems to be also: a transition (2) from 'non_operational' state to 'available' ("The vehicle was previously in need of maintenance")

issues:
- two events have the same name but mean different things. Shouldn't the (2) be called "maintenance_end" for example, to distinguish with the other?
- in any case "maintenance" is vague, and is not consistent with the other events being verbs (e.g. trip_end)

thanks!
vic

**Comment by karcass** [comment]
Yep, it's a little ambiguous.  I'm not sure why nobody flagged it during the 1.0 release process.  We could fix it, but it would be a breaking change.  Since you get to specify the reason (`maintenance`) as well as the state (`available`, `non_operational`), you can still disambiguate them.

**Comment by schnuerle** [comment]
If anyone could create the recommended wording clarification change here or in a PR, that would help move this forward.

**Comment by pierre-bouffort** [comment]
Here is a proposal Micheal:

maintenance - General maintenance that doesn't need to be performed in operator's facilities. 
maintenance_pick_up - Pick for maintenance that has to be performed in operator's facilities.

**Comment by schnuerle** [comment]
This seems a bit related to the removal of the unknown state drafted by @jean-populus which means to clarify if a vehicle is in the PROW or not: https://github.com/openmobilityfoundation/mobility-data-specification/pull/814

I think that's what @pierre-bouffort is getting at with his suggestion, that some maintenance stays in the PROW, and some goes back to a warehouse out of PROW, and that's an important distinction.

I feel that @vilesa1 is saying more that maintenance could be used to mean going into maintenance or returning from maintenance, which is why @marie-x said the resulting state already can clarify this.

So the initial issue seems to be resolved, but Pierre is suggesting a fix to a related issue, right?

**Comment by schnuerle** [comment]
Can @marie-x confirm that this issue will be resolved?

**Comment by marie-x** [comment]
This is in the modes work rather than the agency/provider work - someone (could be me) should audit the modes docs.

**Comment by schnuerle** [comment]
I'll add this as an update to the spec when working on the 2.0 release candidate. Approved by the WGSC.

**Comment by schnuerle** [comment]
This has been added to the dev branch. See it listed in the [event types file](https://github.com/openmobilityfoundation/mobility-data-specification/blob/feature-maintenance/modes/event_types.md#mobility-data-specification-event-types), and for each mode, eg, [micromobility](https://github.com/openmobilityfoundation/mobility-data-specification/blob/feature-maintenance/modes/micromobility.md#vehicle-state-events). 

Descriptions are generic but adequate. 

maintenance | General maintenance
-- | --
maintenance_pick_up | Pick up for maintenance

But should they be updated to 

**maintenance** - General maintenance that doesn't need to be performed in operator's facilities.
**maintenance_pick_up** - Pick for maintenance that has to be performed in operator's facilities.
