### ISSUE TITLE
Adding KWh consumption in /trip endpoints (for both Agency and Provider API)

### ISSUE THREAD

**Issue by tonial** [openmobilityfoundation/mobility-data-specification#643]
### Is your feature request related to a problem? Please describe.

Some cities that uses MDS data to drive their public policies want to have environmental KPIs based on the use of shared mobility.
A typical KPI would be the CO2 equivalent based on the electric device consumption and the city grid KWh to CO2 ratio.
The issue is that the electric consumption will differ :
- with every device (different battery and motors models will give a different consumption per distance traveled, and providers may have different kind of devices in a same city)
- with every trip (depending on the streets slope) 

### Describe the solution you'd like

I think that adding an `Required if Applicable` `consumption` field in the `/trip` endpoints from Provider and Agency API would solve this issue. It would be required for `electric` or `electric_assist` devices.

The field could be `optional` instead, but since most of the cities I work with want this kind of KPIs, it will soon be mandatory for every providers to give the consumption. 

### Is this a breaking change

No, not breaking

### Impacted Spec

 * `agency`
 * `provider`

### Describe alternatives you've considered

A said in the issue description, this CO2 equivalent consumption can be roughly estimated if a provider provides a average consumption per distance traveled for his devices, but it would not allow to handle providers with multiple kinds of devices.

**Comment by tonial** [comment]
Hi @schnuerle.

Thank you for your answer.

It's quite easy to compute the energy consumption : a provider only needs the **battery capacity** in Wh, and the **battery charge used** in percentage points.
When going from 60% to 40% on a 500 Wh battery, you use 20% of the battery capacity : 100 Wh

This does not take into account the city energy generation systems, and it may indeed depend on how and where the batteries are charge but I don't think the place where the batteries are charged will be far enough from the jurisdiction to change the Wh to CO2 ratio of the power grid, so the jurisdiction will be able to give a value to use to compute CO2 KPI from the trips Wh consumption.

About the more concrete data points ;
- **battery charge used during the trip**: it could allow the Agencies to create a KPI on how many trips a scooter can make before requiring a battery swap.
- **battery capacity**: I'm less certain about this one battery capacity... The only use I see for it is to compute the Wh consumption. Since computing the energy consumption is easy (`battery_charge_used x battery_capacity)` I think it's better to give a data point that serves it's own purpose.

I think we could add both **battery charge used during the trip** and **energy consumption**.
 We could use `energy_consumption` instead of `consumption` to make clear what is stored in the field.
 As for the other one, maybe `battery_use` or `battery_use_pct` ?

**Comment by schnuerle** [comment]
We'll be talking about this at today's [Working Group meeting](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2021.06.17-(Joint-Working-Group)).

**Comment by jfh01** [comment]
As promised in the WG call, I've done some outreach to a couple of independent experts I know who work on transportation GHG emissions reduction. A few points to share from those conversations:

* The electricity consumption for light electric vehicles is a small fraction of the total emissions, and is likely dwarfed by embodied carbon (GHGs emitted in the manufacture and eventual disposal of the vehicle) and operational emissions (rebalancing, charging pickups, maintenance, etc.).
* A useful apples-to-apples comparison between modes requires an understanding of the full vehicle lifecycle, longevity, operational model, and other factors across the modes you're trying to compare
* Trip-by-trip analysis is challenging, given the variables of terrain, rider weight, etc. A vehicle with a significantly larger battery might be less efficient in KWh/km, but more carbon efficient overall if it only needs to be charged every three days instead of daily.

The suggestions were, rather than to focus on individual trip-level consumption, to look at:
* Data / metrics to understand vehicle lifespan. Note that vehicles and batteries are often replaced independently and may need to be tracked separately. Especially true in a swappable system.
* Model disclosures for overall GHG footprint that could be done voluntarily or under regulatory mandate
* Cities could require disclosure of operational miles travelled (likely in a truck or van). The 3rd party fleet management tools used by operators could be a source of this data
* Proxy metrics could be helpful in comparing operational emissions. For example "operator moves per vehicle per day":  the number of times on average a vehicle is moved by the operator, whether for charging, rebalancing, or maintenance 
* Calculation methodologies for trips that were likely to have connected with transit
