### ISSUE TITLE
Different rule types used for policies

### ISSUE THREAD

**Issue by jyeo17** [openmobilityfoundation/mobility-data-specification#764]
After investigation of the 11 use cases on https://github.com/openmobilityfoundation/mobility-data-specification/issues/752, we have found that amongst the different companies (Ride Report, Populus, Vianova, Blue Systems), different rule types are used for the Operating Area/ No Riding and No Parking/ Required Parking policies. 

<html>
<body>
<div ccp_infra_version='3' ccp_infra_timestamp='1651579362831' ccp_infra_user_hash='2654098006' ccp_infra_copy_id='828df54c-448e-4e3b-840b-fd4360fe6ac4' data-ccp-timestamp='1651579362831'><html><head><meta name=ProgId content=Excel.Sheet><meta name=Generator content="Microsoft Excel 15"></head><body link="#0563C1" vlink="#954F72">

  | Rule | Populus | Ride Report | Vianova | Blue Systems
-- | -- | -- | -- | -- | --
1 | Operating Area | Count |   |   | Time
2 | No Riding | Time | Count | Count | Time
3 | No Parking | Time | Count | Count | Time
4 | Required Parking |   |   | Count | Time

</body></html></div>
</body>
</html>

This poses the question to operators if 
1. Is it problematic to have to implement different rule types when working with different companies?
2. Is there a rational to pick one rule type rather than the other?

**Comment by bhandzo** [comment]
Yes this is problematic from the operator side. The point of having a standard is that consumers can build a standard implementation that works everywhere. In this case operators need to build logic into their ingest that is specific to the endpoint they are ingesting from, and manage that logic alongside the rest of their integration, keeping it updated as aggregators make changes.

**Comment by marie-x** [comment]
The plan is for the MDS WG to write some consensus-driven guidance mapping use-cases to how that use case should canonically be implemented.

**Comment by jean-populus** [comment]
For point 2 Populus doesn't have strong feelings for having one type of rules versus another. It would not be difficult for us to adapt to whatever the group consensus turns out to be.

@quicklywilliam, @S-eb your thoughts on this?

**Comment by quicklywilliam** [comment]
I wonder if it would be best to add some sort of "prohibited" rule type, rather than implying something is prohibited via a count or time? This would be a lot more intuitive/explicit and evidently covers several major use cases.

**Comment by S-eb** [comment]
> For point 2 Populus doesn't have strong feelings for having one type of rules versus another. It would not be difficult for us to adapt to whatever the group consensus turns out to be.
> 
> @quicklywilliam, @S-eb your thoughts on this?

@jean-populus similar state of mind. We are open to adapt if required. Now there’s difference between rules types so might be interesting to discuss which rule type fit best a given use case

**Comment by mrsimpson** [comment]
Great you bring this up, @jyeo17 !

Imho, (and as we implement in [DB Curbside Management](https://www.deutschebahnconnect.com/produkte/curbside-management)), I see different aspects which the regulation focuses on, resulting in the different rule types:

* *Parking* of an individual vehicle => Limit *duration* how long a vehicle is allowed to be parked => aspect `time`, with the extreme of "not allowed" (duration = 0)
* *Movement* of an individual vehicle => Limit *how fast* a vehicle is allowed to move => aspect `speed`, with the extreme of "no riding" (speed = 0)
* Offering of a particular *fleet* => Limit the availability of vehicles within an area => aspect `count`, with the extreme of "no offering allowed" (count = 0). Of course, usually availability of a vehicle is defined by "a vehicle is parked", but the difference to *parking* is that a  potential violation addresses not a particular vehicle, but the whole fleet. When violating a {{count}} rule, this is only evaluated once per rule (aggregating all vehicles inside the geographies referred to in the rule) and thus creates only max. one compliance violation. Think about a count > 0, say max. 500 vehicles in an operating area. If it's 501, which would be the one to violate the rule? Even more weird: If you had min. 200 vehicles agreed between city and provider but only 199 are parked or rented, which is the one missing 😬 ?

Thus, for DB Curbside Management (which is not on your list (yet) ;) )

  | Rule | DB Curbside 
-- | -- | -- 
1 | Operating Area | Count 
2 | No Riding | Speed 
3 | No Parking | Time 
4 | Required Parking | Time

**Comment by jyeo17** [comment]
Thank you all for your comments and input.
From the previous working group, it seems like there is a general concensus that:

- 'Time' should be used when the rule applies to the vehicle itself
- 'Count' should be used when it concerns controlling the number of vehicles in an area
- 'Speed' should be used when the rule seeks to control the speed of the vehicle

So, by specifying the definitions of the use cases, we have the recommendations below:
<html>
<body>
<div ccp_infra_version='3' ccp_infra_timestamp='1652878018514' ccp_infra_user_hash='2654098006' ccp_infra_copy_id='65c6f4fe-45d9-4f03-aec5-e6c5b38b14ce' data-ccp-timestamp='1652878018514'><html><head><meta name=ProgId content=Excel.Sheet><meta name=Generator content="Microsoft Excel 15"><style>table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	text-align:general;
	vertical-align:bottom;
	border:none;
	white-space:nowrap;
	mso-rotate:0;}
.xl17
	{border:.5pt solid black;}
.xl18
	{font-family:Calibri, sans-serif;
	mso-font-charset:1;
	border:.5pt solid black;}
.xl70
	{font-weight:700;
	border:.5pt solid black;}
</style></head><body link="#0563C1" vlink="#954F72">

  | Rule | Definition of use case | Recommendation
-- | -- | -- | --
1 | Operating Area | Define the boundaries of operation of vehicle (Riding area) | Time
2 | No Riding | Vehicles should not be in the area regardless of status | Time
3 | No Parking | Vehicles should not be parked in these areas (available, reserved, non-operational) | Time
4 | Parking | Vehicles must be parked in these areas. | Time
5 | Parking Time Limit | Vehicles have a limitation of time on parking in these areas. | Time
6 | Speed Limits | Vehicles have a speed limit in these areas. | Speed
7 | Distribution Policies | Rules to control the amount of vehicles in areas | Count
8 | Provider Caps or Minimums | Rules to control the maximum or minimum number of vehicles deployed by a provider | Count

</body></html></div>
</body>
</html>

**Comment by mrsimpson** [comment]
While I unserstand that `speed` is a difficult thing since it's telemetry and not event based, I don't quite understand how something related to time (something you can measure looking at your watch) can relate to the process of riding. 
Outside in the real world:tm: , "riding" is defined by "something is moving" and movement is something you measure by determining its speed.
@jyeo17 Can you shed some light which `time` (value and unit) would be used to define "no riding"? How is this different from "no parking" ?

**Comment by S-eb** [comment]
@mrsimpson Thanks a lot for your comment!

Here our understanding of “time’ is amount of time spent by a device in a given state.
A No Parking rule would result in allowing no more than 0 minutes in the ‘available’ status in a given geography. 
A No riding zone would result in allowing no more than 0 minutes in the ‘on_trip’ status in a given geography.
Does this make sense?

**Comment by quicklywilliam** [comment]
The above table is really helpful and I think the interpretations given are very reasonable. That said, I agree with @mrsimpson that using `time` to cover a No Ride Zone is very unintuitive. And I think it's an orange flag that we are leaving so much up to our differing interpretations. I don't think you should have to read detailed documentation to understand such basic/common policy use case. 

My suggestion is that we take this opportunity to make the Policy API more explicit and use-case driven, such as adding an `[prohibited](https://github.com/openmobilityfoundation/mobility-data-specification/issues/764#issuecomment-1116619404)` rule type. The current implementation is derived from the original design goal of having everything be 100% interpretable via an abstracted state machine interpreter. That goal hasn't matched up with how Policy is used IRL, where implementations can differ greatly and interpretation is often done by humans.

**Comment by mrsimpson** [comment]
@S-eb sorry for taking so long to respond – it took me a while to clear my fingers in order to respond kindly to your question  without sounding rude (which we Germans are said to tend to do ;) )
> Does this make sense?

After two days of picking my words carefully, I'd kindly reply "that depends how you look at it".

If you mean "Is this a change for the better and does it make policies easier to interpret" I'd say "hell no!" ;) Currently, the rule rules have feature a `rule_type` which classifies them. This classification relates to the aspect which shall be governed. I do think it's strange that the same rule type may refer to different `vehicle states` – and equally may make only sende in combination with a particular state (`speed` would only apply to the vehicle state `on_trip`).
If you mean "Can we utilize the unit `time` and the vehicle states to express how long a particular vehicle moves within a city" I'd agree: That makes some sense. Are there other ways to express the same: I [do think that describing which aspect of a vehicle utilization shall be regulated](https://github.com/openmobilityfoundation/mobility-data-specification/issues/764#issuecomment-1123359415) is much better since the vehicle state would be generally independent from the rule type, but *may* be used to further specify particular rules.

I do think we really have to decide about the target audience of an mds policy document. 
- If it's meant to be interpreted by machines implemented by different developers all over the world, I'd expect the written specification to include real world use cases and their mappings to the technical representation so that developers of user-facing interfaces can code it equally.
- If it's meant to be understandable for humans, I'd love to see a disruptive change which allows the use case (like "no riding") to be explicitly stated in the rule (maybe as an enum-value of [`rule type`](https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/policy#rule-types)). Then, we'd ... well also need the written specification to include real world use cases and their mappings to the technical representation so that developers of compliance-checking services can code it equally.

I hope I could make sense with writing that – it's a bit tricky for me as a non-native writer to find the right words, but I tried my best.

@schnuerle I'll take your statement as an invitation and will try to attend tomorrow's meeting

**Comment by jean-populus** [comment]
I'd like to take a step back and see if we have consensus on the Use Case Definitions in https://github.com/openmobilityfoundation/mobility-data-specification/issues/764#issuecomment-1129963329 because this will inform our thinking on speed vs time and using prohibitive rules.

Are the Use Case Definitions how most municipalities and providers are interpreting these rules? In particular **No Parking** means **Vehicles should not be in the area regardless of status**.

**Comment by schnuerle** [comment]
We will be talking about this at this week's [MDS meeting](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2022.06.23-(MDS-Working-Group)).

**Comment by mrsimpson** [comment]
We discussed what is really the problem that different applications map use cases differently into rules.
Our finding was that the engine that interprets the rules has no problem at all with the different mappings: A compliance processor can quite easily evaluate whether a vehicle has violated maximum speeds, stop times, or if a fleet has violated counts based on the transmitted telemetry. 
Rather, the problem lies in the comprehensibility by a humanoid. Therefore, we questioned whether it might not make more sense to leave the API as it is currently designed (optimized for machine-to-machine) and introduce a second interface that focuses on human authoring.
Ideally, a library could then also be provided as a referential implementation that realizes this mapping between use case and policy.

**Comment by jean-populus** [comment]
So it seems like we have consensus on everything except for the No Ride rule.

For the No Ride the description should be broadened to be -

> Vehicles should not be in the area.

Which covers the two use cases discussed during the call

1. Vehicles cannot be ridden in the area but may be dragged into and parked there.
2. Vehicles cannot be ridden in the area nor parked there (no PROW vehicles).

If we want to have just a single [`rule_type`](https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/policy#rule-types), that means for the options -

- `speed` cannot be applied to both use cases
- `time` was considered not intuitive

So that leave `count` as the best option for a No Ride rule. Any thoughts on the recommendation to use `count` as the `rule_type` for a No Ride area?

**Comment by marie-x** [comment]
Lacuna is (for now) using `count`, although we used to use `speed`.  We had to change our compliance measurement mechanisms to include telemetry, but that seems to be working well.  It also means that we can't adjudicate violations in real-time in LA, because telemetry is delayed by up to 24h for privacy reasons.

**Comment by mrsimpson** [comment]
I still can't understand how one can count the process of riding: Riding something is a process (movement over time), it can be measured as speed. What would a "count" rule for a no riding look like? And how would it be differentiated from a no-operating-area for a particular provider?
In the call, a representative of an operator (William?) also brought up the fact that preventing a ride is technically sanctioned on the vehicle => Speed rules would be deployed to the vehicle so it can safely reduce the speed (at most to 0) when entering a no ride area. 
That leaves the issue that speed does not address that the vehicle should *also* not be parked (bullet point 2. on @jean-populus 's list). I strongly recommend that this is expressed as a second rule (of `rule type time, max 0s`): This rule would then be naturally be deployed to the operator's app making it impossible to terminate the rent within this rule.

**Comment by jean-populus** [comment]
You can count vehicles that are `on_trip` to count the process of riding. This works in most cases as trip telemetry and speed isn't usually measured in real-time.

Parking in a No Ride zone isn't how the majority of cities are implementing this policy so I recommend we use `count` for No Ride policies as the primary implementation and include an alternative option for `speed` when parking isn't part of the policy.

**Comment by jyeo17** [comment]
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">So, by specifying the definitions of the use cases, we have the recommendations below:</p><div dir="auto" style="box-sizing: border-box; margin-bottom: 0px !important; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

  | Rule | Definition of use case | Recommendation
-- | -- | -- | --
1 | Operating Area | The vehicle should stay within the areas of operation defined (Riding area).  | Time
2 | No Riding | The vehicle should not be in one of these defined areas regardless of status. | Count
3 | No Parking | The vehicle should not be parked in one of these defined areas in the statuses Available, Reserved and Non-operational. | Time
4 | Parking | The vehicle should be parked in one of these defined areas. | Time
5 | Parking Time Limit | The vehicle should only be parked in one of these defined areas for a limited amount of time. | Time
6 | Speed Limits | The vehicle should operate at a specific maximum speed in these defined areas. | Speed
7 | Distribution Policies | The amount of vehicles spread amongst these defined areas are controlled. | Count
8 | Provider Caps or Minimums | The maximum or minimum amount of vehicles deployed by a provider are controlled. | Count

</div>
</body>
</html>

**Comment by schnuerle** [comment]
Resolved with #786
