### ISSUE TITLE
Add Agency ID: Miami

### ISSUE THREAD

**Issue by HiGregory** [openmobilityfoundation/mobility-data-specification#802]
**Note:** See the [Adding an MDS Agency ID](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Adding-an-MDS-Agency-ID) page for more help.

Opening this issue will allow you as a city or governmental agency get an official agency ID for use across MDS globally, and include in your Requirements URL.

**Fields needed from you for the [agencies.csv file](https://github.com/openmobilityfoundation/mobility-data-specification/blob/main/agencies.csv).**

_All fields are required._

1. **agency_country_iso_code** -
   - US
1. **agency_state** - 
   - FL
1. **agency_city** - Miami
   - Miami
1. **agency_name** - City of Miami
   - City of Miami
1. **agency_id** - MIAM
   - 60efbdb7-024f-480f-b70d-0e0ca79ac614
1. **department_url** - 
   - [City of Miami](https://www.miamigov.com/Home)
1. **requirement_url** -
   -  To Be Added

- Name- Gregory Johnson 
- Company - DataGovs
- Role - Supplier/Vendor

**Comment by schnuerle** [comment]
Hi Greg. For agency_id, we need a UUID. You can use this random one if you'd like: 60efbdb7-024f-480f-b70d-0e0ca79ac614

We can make this update once you have a live requirement_url to be added, otherwise there isn't much value here. The other agencies listed were seeds from our members just to give the file some structure.

**Comment by schnuerle** [comment]
You can reopen if you create a requirement URL for one of your public agencies.
