### ISSUE TITLE
Schema for transport interventions?

### ISSUE THREAD

**Issue by Robinlovelace** [openmobilityfoundation/mobility-data-specification#811]
Apologies for the lack of detail but, having taken a look at schemas here, I wonder if there is interest in a schema for different types of transport interventions? See here for prototype focussed on active travel interventions, e.g. new low traffic area or cycleway: https://acteng.github.io/schema/v1

**Comment by schnuerle** [comment]
Could you explain this a bit more? Are you thinking about the JSON Schema validation? Or is it adding transport interventions into the MDS someplace?

**Comment by Robinlovelace** [comment]
I'm wondering if there would be scope to add transport interventions into the Mobility Data Specification (MDS). Possibility for that? I know of previous work on this but it's quite ad-hoc and there could be value in having an international-facing and maintained spec for such things, although realise it's a big ask!

**Comment by schnuerle** [comment]
Some of this has been discussed to some degree. For example, defining the road structure or intersection structure/capabilities, possibly in a new spec (since it might not fit MDS scope). Also defining sidewalk or curb-adjacent elements has been [discussed](https://github.com/openmobilityfoundation/curb-data-specification/wiki/Web-Conference-2022.12.13-Curb#updates-on-cds-20-and-curb-wg-next-steps) as part of CDS.

We can use this issue to discuss and think about this more in future OMF work.

**Comment by schnuerle** [comment]
Closing for now, but will open a new issue if specific ideas from this list of options come up in future MDS expansion efforts. We are thinking about intersection travel data and curb objects in CDS now.
